'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

interface Report {
  id: number;
  case_id: number;
  case_number: string;
  title: string;
  respondent_name: string;
  status: string;
  report_details: string | null;
  generated_by_name: string;
  created_at: string;
}

export default function ReportsPage() {
  const router = useRouter();
  const [reports, setReports] = useState<Report[]>([]);

  useEffect(() => {
    fetch('/api/cases?status=escalated')
      .then(r => r.json())
      .then(data => {
        const casesWithReports = data.cases || [];
        Promise.all(casesWithReports.map((c: any) =>
          fetch(`/api/cases/${c.id}/report`).then(r => r.json())
        )).then(results => {
          const allReports: Report[] = [];
          results.forEach((r, i) => {
            if (r.reports && r.reports.length > 0) {
              r.reports.forEach((rep: any) => {
                allReports.push({ ...rep, case_number: casesWithReports[i].case_number, title: casesWithReports[i].title, respondent_name: casesWithReports[i].respondent_name, status: casesWithReports[i].status });
              });
            }
          });
          setReports(allReports);
        });
      });
  }, []);

  return (
    <div>
      <h1 className="mb-6 text-2xl font-bold text-slate-900">Filing of Action Reports</h1>

      {reports.length === 0 ? (
        <div className="rounded-xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-400">
          No Filing of Action reports have been generated yet.
        </div>
      ) : (
        <div className="space-y-4">
          {reports.map((r) => (
            <div key={r.id} className="rounded-xl border border-slate-200 bg-white p-5">
              <div className="mb-3 flex items-start justify-between">
                <div>
                  <h3 className="font-semibold text-slate-900">{r.case_number} - {r.title}</h3>
                  <p className="text-sm text-slate-500">Respondent: {r.respondent_name}</p>
                  <p className="text-xs text-slate-400">Generated by {r.generated_by_name} on {new Date(r.created_at).toLocaleString()}</p>
                </div>
                <span className="rounded-full bg-red-100 px-2.5 py-0.5 text-xs font-medium text-red-800">Escalated</span>
              </div>
              <pre className="rounded-lg bg-slate-50 p-4 text-xs text-slate-700 whitespace-pre-wrap max-h-60 overflow-y-auto">
                {r.report_details}
              </pre>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
